### PR TITLE
Feature/add config to repo

### PR DESCRIPTION
**Pull request by stewartie4**
This PR simplifies the deployment process by deploying delegate wallets and nodes freshly with every network deployment.
This way all system tests networks are identical and any erroneous manual config is overridden on a new deployment.
This should also make changes easier to deploy as you simply need to update the actions repo rather than make manual changes in rancher  

System tests change where wallets are also committed to repo: https://github.com/0chain/system_test/pull/220/files

### CODE REVIEW

**Comment by stewartie4** [comment]
@Kishan-Dhakan / @dabasov / @cnlangzi any thoughts?

**Review by Kishan-Dhakan — APPROVED** [review]
Awesome! No more skipping these tests or changing wallet files for different networks 🤌

**Comment by stewartie4** [comment]
last remaining task is to revert ACTIONS_BRANCH variable to master, I will do this before i merge

**Review by Kishan-Dhakan — APPROVED** [review]
LGTM

**Pull request merged**
