### PR TITLE
colored alert

### PR DESCRIPTION
**Pull request by Manali-Jain-squareops**

### CODE REVIEW

**Comment by boddumanohar** [comment]
@Manali-Jain-squareops is this still relevent? Do we have a example of the colored message?

**Comment by Kishan-Dhakan** [comment]
@Manali-Jain-squareops is this PR still relevant?

**Comment by Manali-Jain-squareops** [comment]
yes it is

**Review by shahnawaz-creator — APPROVED** [review]
LGTM

**Pull request merged**
