### PR TITLE
Feature: add "ethereum_node_url" param for "deploy-0chain" workflow

### PR DESCRIPTION
**Pull request by YarikRevich**
Adds opportunity to set custom "ethereum_node_url" param, which is used by 0chain components to perform interactions with Ethereum network

### CODE REVIEW

**Comment by shahnawaz-creator** [comment]
I think your PR needs to get merged along with its dependent repositories. for example 0chain, blobber, 0box, 0dns. otherwise systemtest will break over there.

**Review by Kishan-Dhakan — APPROVED** [review]

**Comment by YarikRevich** [comment]
> I think your PR needs to get merged along with its dependent repositories. for example 0chain, blobber, 0box, 0dns. otherwise systemtest will break over there. @Kishan-Dhakan @YarikRevich

Added input is not required to be set by other workflows, so there won't be any breaks, otherwise anytime we'll be able to rollback changes

**Comment by stewartie4** [comment]
I agree with @shahnawaz-creator 

This has broken every repo's ability to run manual system tests now as you've changed the params, but not updated 
https://github.com/0chain/actions/blob/master/.github/workflows/manual_system_tests.yml#L272
nor other repos such as
https://github.com/0chain/0chain/blob/staging/.github/workflows/system_tests.yml#L51

In addition, devs can no longer specify a miner/sharder image on their branch.

I should have been added as a reviewer on this.
I will raise PRs to fix the issue

**Review by stewartie4 — COMMENTED** [review]
I agree with @shahnawaz-creator 

This has broken every repo's ability to change miner image on manual system tests now as you've changed the params, but not updated 
https://github.com/0chain/actions/blob/master/.github/workflows/manual_system_tests.yml#L272
nor other repos such as
https://github.com/0chain/0chain/blob/staging/.github/workflows/system_tests.yml#L51

In addition, devs can no longer specify a miner/sharder image on their branch.

I should have been added as a reviewer on this.
I will raise PRs to fix the issue

**Review by stewartie4 — COMMENTED** [review]
Issue fixed after revert:
image

**Pull request merged**
